#!/usr/bin/env groovy
pipeline {
    agent { docker { image 'maven:3.5.3' } }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh '''
                	cd joylink-userms
                	ls
                	mvn clean package -Dmaven.test.skip=true
                	'''
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'java -version'
                sh 'java -jar joylink-userms/target/*.jar'
            }
        }
    }
	post {
		always {
			echo 'always do'
		}
		success {
			echo 'success do'
		}
		failure {
			echo 'failure do'
		}
		unstable {
			echo 'unstable do'
		}
		changed {
			echo 'changed do'
		}
	}
}